<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="Microsoft.ML.Tokenizers" />
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.O200kBase" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Grimora.Store.Tests" />
  </ItemGroup>
</Project>
